### ISSUE TITLE
eglGetDisplay function crashes on OSX

### ISSUE THREAD

**Issue by whj198579** [powervr-graphics/Native_SDK#21]
This function works well on OSX 10.12.6, but crashes on OSX 10.13.1.
![image](https://user-images.githubusercontent.com/3286566/34348579-accc7448-ea46-11e7-9105-15c6be4aa2be.png)

**Comment by senthuran-lkn** [comment]
Hi thank you for  reporting the issue. It seems like the function pointer is null.
Can you provide us the full log please, which you can copy from the xcode output  window.  Also have you tried other examples from the sdk? do they have the same problem for OSX 10.13.1.

**Comment by wang-bin** [comment]
Same crash here. 4.3 sdk and other EGL implementations on macOS works fine


    #0 0x7fff6ca82ded in strstr (libsystem_c.dylib:x86_64+0x5aded)
    #1 0x10fe4ba8f in wrap_strstr (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x17a8f)
    #2 0x11bbf3aa5 in host::CapabilityChecker::supports_extension(char const*) const (libEGL.dylib:x86_64+0xadaa5)
    #3 0x11bbd8a39 in egl::State::send_system_report() (libEGL.dylib:x86_64+0x92a39)
    #4 0x11bbd865e in egl::State::initialize() (libEGL.dylib:x86_64+0x9265e)
    #5 0x11bbd843d in egl::initialize_global_state() (libEGL.dylib:x86_64+0x9243d)
    #6 0x11bbd42d2 in eglGetDisplay (libEGL.dylib:x86_64+0x8e2d2)

**Comment by bin-zhao** [comment]
Is this issue fixed? I encounter the same problem, and my system version is 10.13.3 (17D47).

**Comment by senthuran-lkn** [comment]
we are looking in to this issue.
